fix: improve dev-tools release process (#2687)

diff --git a/infra/build/Makefile b/infra/build/Makefile
--- a/infra/build/Makefile
+++ b/infra/build/Makefile
@@ -1,4 +1,4 @@
-# Copyright 2019-2023 Google LLC
+# Copyright 2019-2024 Google LLC
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -115,6 +115,11 @@ build-image-developer-tools:
 
 .PHONY: release-image-developer-tools
 release-image-developer-tools:
+	if [[ -z "${GITHUB_SHA}" ]]; then
+	  echo "ERROR: Missing GITHUB_SHA for the release"
+		exit 1
+	fi
+
 	docker tag ${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
@@ -138,6 +143,10 @@ release-image-developer-tools:
 	docker tag ${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
+
+	docker tag ${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
+  ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS}:${DEP_TAG_PREFIX}${GITHUB_SHA}
 
 	docker tag ${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
@@ -163,6 +172,10 @@ release-image-developer-tools:
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 
+	docker tag ${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
+  ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_TOOLS_JENKINS}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+
 	docker tag ${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
@@ -187,6 +200,10 @@ release-image-developer-tools:
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 
+	docker tag ${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
+  ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_LIGHT}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+
 	docker tag ${DOCKER_IMAGE_DEVELOPER_KRM}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS}
@@ -210,6 +227,10 @@ release-image-developer-tools:
 	docker tag ${DOCKER_IMAGE_DEVELOPER_KRM}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
   ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
 	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DEP_TAG_PREFIX}${DOCKER_TAG_MINOR_VERSION_DEVELOPER_TOOLS}
+
+	docker tag ${DOCKER_IMAGE_DEVELOPER_KRM}:${DOCKER_TAG_VERSION_DEVELOPER_TOOLS} \
+  ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DEP_TAG_PREFIX}${GITHUB_SHA}
+	docker push ${REGISTRY_URL}/${DOCKER_IMAGE_DEVELOPER_KRM}:${DEP_TAG_PREFIX}${GITHUB_SHA}
 
 # The following tasks are provided as examples and aren't invoked from this
 # repository directly. These three make targets are the only targets that
